### ISSUE TITLE
It is really hard to find private charms owned by a team.

### ISSUE THREAD

**Issue by mhilton** [canonical-web-and-design/charmhub.io#172] opened 2019-11-08 16:27 UTC
**Describe the bug**
I have a team "jaas-charmers" that owns a number of non-public charms. These charms can theoretically be found at https://jujucharms.com/u/jaas-charmers. If one is not logged in then this page redirects to https://jaas.ai/u/jaas-charmers which is a 404 and gives no clues that one needs to log in to see any charms. If one knows that one has to log in, and to log in one should click on "Your Models" (That is hardly obvious), and the "Login". One ends up on the https://jujucharms.com/new page. It is only after re-entering the URL you first thought of that you can actually see a list of charms owned by the team.

**To Reproduce**
You will need to be a member of yellow for this to complete for you.

1. Go to https://jujucharms.com/u/jaas-charmers
2. Get redirected to https://jaas.ai/u/jaas-charmers
3. Click on "Your Models"
4. Click Login and authenticate.
5. Edit the address to be https://jujucharms.com/u/jaas-charmers
6. Observe the list of charms you were looking for.

**Expected behavior**
Going to the https://jujucharms.com/u/jaas-charmers URL should provide me with a simple mechanism to login and see the page contents.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser firefox
 - Version 70.0.1 (64-bit)

**Comment by Lukewh** [comment] 2020-05-15 09:44
I don't believe this should be in the charmhub.io repo - the issue is with the way jaas.ai and jujucharms.com currently work.

Charmhub.io will not have the concept of /u/<name> - this will remain part of the jaas.ai/ juju.is/ jujucharms.com world.

Closing, feel free to transfer back to jaas.ai and reopen.

**Closed by Lukewh** 2020-05-15 09:44 UTC
