### ISSUE TITLE
Charmhub discourse urls do no go into browser's navigation history

### ISSUE THREAD

**Issue by sed-i** [canonical-web-and-design/charmhub.io#1242] opened 2022-02-01 16:53 UTC
When navigating around in discourse.charmhub.io, the urls I visit to do not go into the browser's history: the back button remains grayed out all along.

**Comment by jkfran** [comment] 2022-02-01 17:50
Hi @sed-i. I tried to reproduce this problem and it is not happening to me (Firefox and Chrome). Could you tell us what browser are you using and if it happening on other Discourses like https://forum.snapcraft.io or https://discourse.ubuntu.com/?

Thank you.

**Comment by sed-i** [comment] 2022-02-01 22:54
I got an email from charmhub with latest changes, and I clicked on `View topic`, for example:
- https://discourse.charmhub.io/t/olm-how-to-guides/5334/1
- https://discourse.charmhub.io/t/the-charmed-operator-lifecycle-manager-olm-docs/1087/1

From this point URLs do no go into history. Occasionally. I just noticed this happens only sometimes.
I thought it's related to my Firefox privacy addons but no, I reproduced the same with Brave.

**Comment by anthonydillon** [comment] 2022-02-02 15:22
It looks like this is a [bug in discourse](https://meta.discourse.org/t/back-button-history-not-properly-working/122183/8). Which was [fixed in 2.9](https://github.com/discourse/discourse/commit/de6edf9e4e5675db0e4bf13000402ec60ae01cd3). You can fix this content by adding the full link to content and not just the id to the topic.

**Closed by anthonydillon** 2022-02-02 15:22 UTC
Labels: Priority: Medium
