### ISSUE TITLE
Configure tab doesn't highlight default selection

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/charmhub.io#1024] opened 2021-05-27 08:45 UTC
![Screenshot 2021-05-27 at 09.39.03.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/5fae9cfa-4762-424c-a3ad-83a3ffedb752)

See image, in this case the "configure" tab opens cluster-name and it should be in the active state, like this:

![Screenshot 2021-05-27 at 09.45.35.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/8d77b6db-0b05-475b-9e97-5239d0399f19)

**Comment by steverydz** [comment] 2021-05-27 08:48
Closing. Duplicate of https://github.com/canonical-web-and-design/charmhub.io/issues/957

**Closed by steverydz** 2021-05-27 08:48 UTC
