### ISSUE TITLE
No scroll bar with 'I don't care about cookies' extension

### ISSUE THREAD

**Issue by tomwardill** [canonical-web-and-design/charmhub.io#809] opened 2021-02-12 10:49 UTC
This was replicated on Firefox, but might also apply to equivalent Chrome add ons.

If you have the 'I don't care about cookies' extension installed, it will remove the 'tracker options' pop over.
In this case, the JS never executes and the scrollbar on the front page is never displayed.

Either disabling the extension for charmhub.io or using a private window will display the pop up and allow the scroll bar to appear.

Screenshot of front page that is interactive but with no scrollbar:
![image](https://user-images.githubusercontent.com/53100/107759274-fa8eac00-6d1f-11eb-9dd8-92d4b75e5f6e.png)

**Comment by nottrobin** [comment] 2021-02-15 22:22
@anthonydillon you had an explanation of why this is happening right? Can you write it down for me? I'm curious.

**Comment by anthonydillon** [comment] 2021-02-15 23:53
Interesting, at first I thought it might be the scrollbar disabling from the cookie model but it doesn't seem to be implemented on charmhub.io. I then installed "I don't care about cookies" on Firefox 85 and visited the site and the cookie policy did not render but and scroll bars were visible and usable.

@tomwardill Would you mind trying again, and seeing if you can replicate this issue?

**Comment by Roadmaster** [comment] 2021-02-16 16:00
I was also bit by this, I think the first place where I noticed it was issuing a search for "kubernetes" and I couldn't scroll down the results https://charmhub.io/?q=kubernetes . After that, simply going to a charm's page directly (https://charmhub.io/charmed-kubernetes) also was scroll-less, so I couldn't e..g read the rest of the readme. I disabled the extension, then reenabled it, and that brought back the scrollbars. Now I can't reproduce the problem :(

**Comment by nottrobin** [comment] 2021-02-16 17:03
Could this have been a weird bug in the extension that has now been fixed?

There's a few hints of similar things around the internet:

https://forum.palemoon.org/viewtopic.php?t=22598#p171363
https://support.mozilla.org/en-US/questions/1268532#answer-1253112

but nothing as solid as an issue against the project.

**Comment by anthonydillon** [comment] 2021-02-16 17:32
I can replicate it now. It's caused by the `u-scroll-lock` class introduced by the cookie policy. This stops the page from scrolling as it expects the modal to be there but the "I don't care about cookies" extension simply selects a huge list of class names including "cookie-policy" and `display: none !important;` it.

The only solution I can think of is to remove the scroll locking from the cookie policy module.

**Comment by anthonydillon** [comment] 2021-02-18 12:09
@tomwardill thank you for reporting this issue. A fix has been released to production.

**Closed by anthonydillon** 2021-02-18 12:09 UTC
Labels: question
