### ISSUE TITLE
Put labels on charms that are on operator framework

### ISSUE THREAD

**Issue by jkfran** [canonical-web-and-design/charmhub.io#1090] opened 2021-07-16 08:22 UTC
All the previous charms with the Operator Framework label are now marked as operator frameworks on the API and new revisions of other charms will show it as well.
```
$ curl -s "https://api.charmhub.io/v2/charms/info/graylog-k8s?fields=default-release.revision" | jq '."default-release"'.revision.attributes
{
  "framework": "operator"
}
```

**Comment by danielmutis** [comment] 2021-07-26 15:03
We will share this on the dev cross team to see what the decision should be on whether to bring back all the badges or just to display the ones that are operator framework. 

The issue is that we can't be sure of whether  charm that isn't operator framework is reactive or not.

**Comment by cristinadresch** [comment] 2021-09-24 14:20
Latest designs https://zpl.io/aNxDqzQ
Keep in mind we dont need the functionality label, or reactive. Just operator framework.

**Comment by long-chung** [comment] 2021-09-30 08:27
Moving the label next to the badge made the area very cramped and didn't work well on smaller cards.
Therefore I am proposing to close this issue and keep to the existing design done my Spencer.

**Closed by long-chung** 2021-09-30 08:27 UTC

**Comment by heitorPB** [comment] 2021-09-30 12:43
@long-chung can't this label be on the charm page?

As someone that uses Juju in production, this information is very important to me. There's really no way to have it in CharmHub?

As an end user: i'd like to see this information in the charm page and also in the search page for charms.

Can't a small icon be added to the charm's card in the search? It looks there's plenty of space to add just after the `VM` or `K8s` icon:
![charmhub](https://user-images.githubusercontent.com/13461702/135457060-24699a9c-2c30-4ee4-b264-e32736290dd1.png)

**Comment by long-chung** [comment] 2021-09-30 12:48
@heitorPB The plan was to explore putting the label next to the icon, but the space didn't allow for this. So to sum up, we will be adding the label as per the previous designs, just not at the bottom next to the icons.

**Comment by heitorPB** [comment] 2021-09-30 12:57
Thanks for the comment, @long-chung!

Is there a way I can see a preview of this design? Or this is internal to your team only?

**Comment by long-chung** [comment] 2021-09-30 12:59
@heitorPB Here you go

![Charmhub homepage - labels](https://user-images.githubusercontent.com/68847062/135459620-73057eed-6c94-4afc-a09f-70b55e32b34b.png)

**Comment by heitorPB** [comment] 2021-09-30 13:18
Oh, nice!

Is this information also in the charm's page? Or will be only in the search page?

**Comment by long-chung** [comment] 2021-10-05 09:38
@heitorPB Sorry for the late reply, just needed to confirm some things with the team.
Yes the label will be in the detail page, we have a design for this but may revisit its positioning at a later date.
