### ISSUE TITLE
Clicking on 'see more operators' new button deselect 'featured' but doesn't display any operators

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/charmhub.io#566] opened 2020-11-11 09:21 UTC
When clicking on this button:
![Screenshot 2020-11-11 at 09.19.34.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/bc361ff1-cf66-4d34-b305-7b40a0bade46)

The page refreshes deselecting "featured" as supposed to but the page doesn't return any operator.

**Comment by steverydz** [comment] 2020-11-11 09:29
Duplicate of https://github.com/canonical-web-and-design/charmhub.io/issues/565

**Closed by steverydz** 2020-11-11 09:29 UTC
